<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Настройки</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php if ($params['errors']): ?>
    <?php foreach($params['errors'] as $error): ?>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php echo $error ?>              
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<?php if ($params['success']): ?>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php echo $params['success']; ?>            
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
            <form role="form" action="" method="POST">
                <div class="row">
                    <div class="col-lg-6">     
                        <div class="form-group">
                            <label>Сложность минимальная</label>
                            <input class="form-control" type="number" required name="min" value="<?php echo $params['settings']['min']->getValue() ?>" >
                        </div>           
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Сложность максимальная</label>
                            <input class="form-control" required type="number"  name="max" value="<?php echo $params['settings']['max']->getValue() ?>" >
                        </div>
                    </div>
                    <div class="col-lg-12" style="border-top: 1px solid; margin-top: 10px; padding-top: 20px">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Сохранить</button>                        
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
