<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Тестирование</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
            <form role="form" action="/index/test" method="POST" id="test-form">
                <div class="row">
                    <div class="col-lg-12">     
                        <div class="form-group">
                            <label>Уровень интеллекта</label>
                            <input class="form-control" id="level" type="number" required name="level" value="0" >
                        </div>           
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Запустить тест</button>                        
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
            <div class="row" style="display: none" id="test_result">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>№</th>
                                            <th>ID</th>
                                            <th>Использовался, раз</th>
                                            <th>Сложность</th>
                                            <th>Ответ</th>
                                        </tr>
                                    </thead>
                                    <tbody id="table_body">
                                    </tbody>
                                </table>
							</div>
						</div>
					</div>
				</div>
			</div>
<div class="row" id="msg" style="display: none">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p class="lead">Тестируемый ответил правильно на <span id="success_count"></span> вопросов из <span id="all_count"></span>.</p>
            </div>
        </div>
    </div>
</div> 
